"""Add full_text_vector to documents

Revision ID: 1e266e194a12
Revises: c66ed36b74f3
Create Date: 2024-09-10 14:44:05.861497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e266e194a12'
down_revision: Union[str, None] = 'c66ed36b74f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new column for full text vector
    op.add_column('documents', sa.Column('full_text_vector', sa.JSON(), nullable=True))

    # Alter the type of summary_vector column with explicit casting
    op.execute("ALTER TABLE documents ALTER COLUMN summary_vector TYPE JSON USING summary_vector::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the type of summary_vector column with explicit casting back to VARCHAR
    op.execute("ALTER TABLE documents ALTER COLUMN summary_vector TYPE VARCHAR USING summary_vector::text")

    # Drop the full_text_vector column
    op.drop_column('documents', 'full_text_vector')
    # ### end Alembic commands ###
