"""Add full_text column to documents table

Revision ID: 455b29fd0664
Revises: d8f3a13fc131
Create Date: 2024-09-11 22:28:24.514254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '455b29fd0664'
down_revision: Union[str, None] = 'd8f3a13fc131'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('full_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'full_text')
    # ### end Alembic commands ###
