"""Add summary fields to documents table

Revision ID: c66ed36b74f3
Revises: aea6c772d66a
Create Date: 2024-09-09 20:03:10.581768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66ed36b74f3'
down_revision: Union[str, None] = 'aea6c772d66a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('summary_vector', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'summary_vector')
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
